#!/bin/bash

PACKAGE="batman-adv"
REMOTE="https://git.open-mesh.org/batman-adv.git"
TAG="v2025.4"
KMOD_VERSION="2025.4"
PKG_RELEASE_PREFIX="0~tecff"
PKG_RELEASE="1"
BUILD_ROOT="/tmp/batman-adv-build"
MAINTAINER="rotanid"
PKGLICENSE="GPL2"
PKGGROUP="net"
PKGDESC="B.A.T.M.A.N. advanced external module"

RUNNING_DISTRO="$(lsb_release -s -i)"
RUNNING_DISTRO_VERSION="$(lsb_release -r -s)"
RUNNING_KERNEL_REL=$(uname -r)
if [[ "$RUNNING_DISTRO" = "Debian" ]]; then
	if [[ "$RUNNING_KERNEL_REL" = "6.12."* ]]; then
		# trixie
		REQUIRED_KERNEL=$(dpkg -s linux-image-amd64 | grep "^Depends" | cut -d" " -f2)
	elif [[ "$RUNNING_KERNEL_REL" = "6.1.0"* ]]; then
		# bookworm
		REQUIRED_KERNEL=$(dpkg -s linux-image-amd64 | grep "^Depends" | cut -d" " -f2)
	elif [[ "$RUNNING_KERNEL_REL" = "5.10.0"* ]]; then
		# bullseye
		REQUIRED_KERNEL=$(dpkg -s linux-image-amd64 | grep "^Depends" | cut -d" " -f2)
	else
		echo "the currently running kernel version ( $RUNNING_KERNEL_REL ) is not supported by this build script."
		exit 1
	fi
	TARGET_KERNEL=$(echo $REQUIRED_KERNEL | sed "s/linux-image-//")
else
	echo "the running distro is not supported."
	exit 1
fi
REQUIRES="${REQUIRED_KERNEL}"

if [[ "$RUNNING_DISTRO_VERSION" = "11"* ]]; then
	# Debian Bullseye
	PKG_RELEASE="${PKG_RELEASE_PREFIX}~deb11u${PKG_RELEASE}"
elif [[ "$RUNNING_DISTRO_VERSION" = "12"* ]]; then
	# Debian Bookworm
	PKG_RELEASE="${PKG_RELEASE_PREFIX}~deb12u${PKG_RELEASE}"
elif [[ "$RUNNING_DISTRO_VERSION" = "13"* ]]; then
	# Debian Trixie
	PKG_RELEASE="${PKG_RELEASE_PREFIX}~deb13u${PKG_RELEASE}"
else
	echo "the currently running $RUNNING_DISTRO version ( $RUNNING_DISTRO_VERSION ) is not supported by this build script."
	exit 1
fi

check() {
	REQUIRED=0

	# check kernel version in vermagic
	local KMOD_VERMAGIC=$(/sbin/modinfo -k $TARGET_KERNEL batman-adv --field vermagic | awk '{ print $1 }')
	if [[ $KMOD_VERMAGIC != $TARGET_KERNEL ]]; then
		echo "[-] Kernel version changed (${KMOD_VERMAGIC} to ${TARGET_KERNEL})."
		REQUIRED=1
	fi

	# check kmod version
	local KMOD_CURRENT=$(/sbin/modinfo -k $TARGET_KERNEL batman-adv --field version)

	/usr/bin/dpkg --compare-versions "$KMOD_CURRENT" "eq" "$KMOD_VERSION"
	local CODE=$?
	if [ $CODE -ne 0 ]; then
		echo "[-] batman-adv version changed (${KMOD_CURRENT} to ${KMOD_VERSION})."
		REQUIRED=1
	fi

	exit $REQUIRED
}

prepare() {
	rm -rf $BUILD_ROOT
	git clone "$REMOTE" "$BUILD_ROOT"
	cd $BUILD_ROOT
	git switch --detach "$TAG"

	# apply patches if they exist
	if [ -d "/usr/src/${PACKAGE}_patches" ] && [ "$(ls -A /usr/src/${PACKAGE}_patches/)" ]; then
		git am /usr/src/${PACKAGE}_patches/*
	fi
}

build() {
	cd $BUILD_ROOT
	export KERNELPATH=/lib/modules/$TARGET_KERNEL/build
	# strip debug info
	export INSTALL_MOD_STRIP=1
	# build (including deprecated DEBUGFS & SYSFS interfaces)
	make -j$(nproc)
}

install() {
	cd $BUILD_ROOT
	echo ${PKGDESC} > description-pak
	checkinstall -y --nodoc \
		--pkgname "${PACKAGE}" \
		--pkgversion "${KMOD_VERSION}" \
		--pkgrelease "${PKG_RELEASE}" \
		--pkgsource "${REMOTE}" \
		--pkglicense "${PKGLICENSE}" \
		--pkggroup "${PKGGROUP}" \
		--maintainer "${MAINTAINER}" \
		--requires "${REQUIRES}" \
		--fstrans=no
	depmod -a
}

if [ "$1" = "check" ]; then
	check
else
	prepare
	build
	if [ "$?" != "0" ]; then
		echo "build may have failed."
		exit 1
	fi
	install
fi
