#!/bin/bash

PACKAGE="batctl"
REMOTE="git://git.open-mesh.org/batctl.git"
TAG="v2018.4"
TARGET_VERSION="2018.4"
PKG_RELEASE="2"
BUILD_ROOT="/usr/src/batctl"
MAINTAINER="rotanid"
PKGLICENSE="GPL2"
PKGGROUP="net"
PKGALTSRC="https://git.open-mesh.org/batctl.git"
PKGDESC="B.A.T.M.A.N. advanced control and management tool"

REQUIRES="libnl-genl-3-200"

check() {
	REQUIRED=0

	local CURRENT_VERSION=$(batctl -v | awk '{ print $2 }')
	/usr/bin/dpkg --compare-versions "$CURRENT_VERSION" "eq" "$TARGET_VERSION"
	local CODE=$?
	if [ $CODE -ne 0 ]; then
		echo "[-] batctl version changed (${CURRENT_VERSION} to ${TARGET_VERSION})."
		REQUIRED=1
	fi

	exit $REQUIRED

}

prepare() {
	rm -rf $BUILD_ROOT
	git clone "$REMOTE" "$BUILD_ROOT"
	cd $BUILD_ROOT
	git checkout "$TAG"
	
	# apply patches if they exist
	if [ "$(ls -A /usr/src/${PACKAGE}_patches/)" ]; then
		git am /usr/src/${PACKAGE}_patches/*
	fi
}

build() {
	cd $BUILD_ROOT
	make -j$(nproc)
}

install() {
	cd $BUILD_ROOT
	echo ${PKGDESC} > description-pak
	checkinstall -y --nodoc \
		--pkgname "${PACKAGE}" \
		--pkgversion "${TARGET_VERSION}" \
		--pkgrelease "${PKG_RELEASE}" \
		--pkgsource "${REMOTE}" \
		--pkgaltsource "${PKGALTSRC}" \
		--pkglicense "${PKGLICENSE}" \
		--pkggroup "${PKGGROUP}" \
		--maintainer "${MAINTAINER}" \
		--requires "${REQUIRES}" \
		--fstrans=no
}

if [ "$1" = "check" ]; then
	check
else
	prepare
	build
	install
fi
