#!/bin/bash
# this script backs up important data on tecff server gw02 
# dependencies: duplicity

BSRV="backup0.nlams0.conemu.net"
BUSR="b_freifunkaltdorf_gw02"
BPATH="/data/duplicity"
LOGPATH="/var/log/duplicity-gw02.log"

echo >> ${LOGPATH}
echo "===============================================================" >> ${LOGPATH}
echo "NEW BACKUP STARTS: $(date)" >> ${LOGPATH}

for dir in /var/local/tecff-raw /var/lib/hopglass-server; do
	duplicity full --no-encryption $dir sftp://${BUSR}@${BSRV}/${BPATH}/$dir >> ${LOGPATH}
	duplicity remove-older-than 4W --force sftp://${BUSR}@${BSRV}/${BPATH}/$dir >> ${LOGPATH}
done
