#!/bin/bash
# this script copies information about nodes from a B.A.T.M.A.N. gateway server to a webserver
# dependencies: openssh-client

RHOST="web01.tecff.de"
LDIR="/var/local"
RDIR="/var/www/html"
# copy to webserver
scp -r $LDIR/tecff-raw/* root@$RHOST:$RDIR/data/
