#!/bin/bash
# this script copies gluon firmware images to their public distribution points
# dependencies: sshfs, rsync

SRVFTP="ftp.freifunk-altdorf.de"
SRVFTP_USR="21271-ffafw"
SRVFTP_MNT="/mnt/fw1.tecff.de-sftp"
SRVSSH="gw02.tecff.de"
SRVSSH_USR="root"
SRVSSH_PATH="/var/www/html/fw"
if [ ! -x "$(which sshfs)" ] || [ ! -x "$(which rsync)" ]; then
	echo "one of the dependencies is missing!"
	exit 1
fi
if [ ! "$#" -eq 1 ] || [ ! -d "$1" ]; then
	echo "please specify the source directory as the first parameter"
	exit 1
fi
SRC="$1"
if [[ "$SRC" =~ ^.+xperimental.+$ ]]; then
	BRANCH="experimental"
elif [[ "$SRC" =~ ^.+table.+$ ]]; then
	BRANCH="stable"
fi
if [ -z "$BRANCH" ]; then
	echo "the source directory doesn't seem to be correct, it has to contain either experimental or stable"
	exit 1
fi
if [ ! -d "$SRC/modules" ] || [ ! -d "$SRC/images/factory" ] || [ ! -d "$SRC/images/sysupgrade" ]; then
	echo "couldn't find at least one of the necessary directories: modules, images/factory, images/sysupgrade"
	exit 1
fi
MANIFEST="$SRC/images/sysupgrade/${BRANCH}.manifest"
if [ ! -f "$MANIFEST" ]; then
	echo "manifest missing: $MANIFEST"
	exit 1
fi
SIGCOUNT="$(sed -e '1,/^---/d' $MANIFEST | wc -l)"
if ([ "$BRANCH" == "experimental" ] && [ "$SIGCOUNT" -lt 2 ]) || ([ "$BRANCH" == "stable" ] && [ "$SIGCOUNT" -lt 3 ]); then
	echo "can't find enough signatures on the manifest file: $MANIFEST"
	exit 1
fi

# prompt for SFTP password
read -p "Please enter the password for sftp user $SRVFTP_USR on server ${SRVFTP}: " SRVFTP_PW
if [ -z "$SRVFTP_PW" ]; then
	echo "you haven't specified a password"
	exit 1
fi

echo "are you sure you backed up the old $BRANCH firmware on the update servers?"
echo "it will be overwritten if you dont interrupt now!"
sleep 5

# ssh copy
echo "starting ssh copy... (needs ssh agent redirection)"
rsync -rltv --delete $SRC/images/factory/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/$BRANCH/factory/
rsync -rltv --delete $SRC/images/sysupgrade/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/$BRANCH/sysupgrade/
rsync -rltv $SRC/modules/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/modules/

# ftp copy
echo "starting sftp copy..."
[ ! -d "$SRVFTP_MNT" ] && mkdir $SRVFTP_MNT
echo $SRVFTP_PW | sshfs -o password_stdin $SRVFTP_USR@$SRVFTP:/ $SRVFTP_MNT
if [ ! -d "$SRVFTP_MNT/modules" ] || [ ! -d "$SRVFTP_MNT/$BRANCH" ]; then
	echo "necessary files are missing on the sftp server, maybe it's the wrong server?"
	exit 1
fi
rsync -rltv --delete $SRC/images/ $SRVFTP_MNT/$BRANCH/
rsync -rltv $SRC/modules/ $SRVFTP_MNT/modules/
echo "sftp copy finished, disconnecting/unmounting..."
fusermount -u $SRVFTP_MNT

echo "finished."
