#!/bin/bash
# this script is used on a B.A.T.M.A.N. gateway to change the routing of some ports so the traffic doesn't got through the vpn provider
# dependencies: iptables, iproute2

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
	echo "missing parameters! ((up|down), BRIDGEIF, INETIF)"
	exit 1
fi

BRIDGEIF="$2"
INETIF="$3"
TCPPORTS="80,443,25,465,587,143,993,110,995,1194,1293"
UDPPORTS="500,1194,1293,4500"

if [ "$1" == "up" ]; then
	iptables -t mangle -N DIRECT
	iptables -t mangle -A DIRECT --dst 192.168.0.0/16 -j RETURN
	iptables -t mangle -A DIRECT --dst 172.16.0.0/12 -j RETURN
	iptables -t mangle -A DIRECT --dst 10.0.0.0/8 -j RETURN
	iptables -t mangle -A DIRECT --dst 169.254.0.0/16 -j RETURN
	iptables -t mangle -A DIRECT --jump MARK --set-mark 1
	# TCP
	iptables -t mangle -A PREROUTING -i ${BRIDGEIF} -p tcp -m multiport --dports ${TCPPORTS} -j DIRECT
	iptables -t nat -A POSTROUTING -o ${INETIF} -p tcp -m multiport --dports ${TCPPORTS} -m comment --comment "000 Masquerade traffic for some ports" -j MASQUERADE
	iptables -A FORWARD -i ${BRIDGEIF} -o ${INETIF} -p tcp -m multiport --dports ${TCPPORTS} -m comment --comment "000 Allow bridge to eth0 forwarding for some ports" -j ACCEPT
	iptables -A FORWARD -i ${INETIF} -o ${BRIDGEIF} -p tcp -m multiport --sports ${TCPPORTS} -m comment --comment "000 Allow eth0 to bridge forwarding for some ports" -j ACCEPT
	# UDP
	iptables -t mangle -A PREROUTING -i ${BRIDGEIF} -p udp -m multiport --dports ${UDPPORTS} -j DIRECT
	iptables -t nat -A POSTROUTING -o ${INETIF} -p udp -m multiport --dports ${UDPPORTS} -m comment --comment "000 Masquerade traffic for some ports" -j MASQUERADE
	iptables -A FORWARD -i ${BRIDGEIF} -o ${INETIF} -p udp -m multiport --dports ${UDPPORTS} -m comment --comment "000 Allow bridge to eth0 forwarding for some ports" -j ACCEPT
	iptables -A FORWARD -i ${INETIF} -o ${BRIDGEIF} -p udp -m multiport --sports ${UDPPORTS} -m comment --comment "000 Allow eth0 to bridge forwarding for some ports" -j ACCEPT
	ip rule del fwmark 1 >/dev/null 2>&1
	ip rule add fwmark 1 table main
else
	iptables -t mangle -D PREROUTING -i ${BRIDGEIF} -p tcp -m multiport --dports ${TCPPORTS} -j DIRECT
	iptables -t mangle -D PREROUTING -i ${BRIDGEIF} -p udp -m multiport --dports ${UDPPORTS} -j DIRECT
	iptables -t mangle -F
	iptables -t mangle -X DIRECT
	iptables -t nat -D POSTROUTING -o ${INETIF} -p tcp -m multiport --dports ${TCPPORTS} -m comment --comment "000 Masquerade traffic for some ports" -j MASQUERADE
	iptables -D FORWARD -i ${BRIDGEIF} -o ${INETIF} -p tcp -m multiport --dports ${TCPPORTS} -m comment --comment "000 Allow bridge to eth0 forwarding for some ports" -j ACCEPT
	iptables -D FORWARD -i ${INETIF} -o ${BRIDGEIF} -p tcp -m multiport --sports ${TCPPORTS} -m comment --comment "000 Allow eth0 to bridge forwarding for some ports" -j ACCEPT
	iptables -t nat -D POSTROUTING -o ${INETIF} -p udp -m multiport --dports ${UDPPORTS} -m comment --comment "000 Masquerade traffic for some ports" -j MASQUERADE
	iptables -D FORWARD -i ${BRIDGEIF} -o ${INETIF} -p udp -m multiport --dports ${UDPPORTS} -m comment --comment "000 Allow bridge to eth0 forwarding for some ports" -j ACCEPT
	iptables -D FORWARD -i ${INETIF} -o ${BRIDGEIF} -p udp -m multiport --sports ${UDPPORTS} -m comment --comment "000 Allow eth0 to bridge forwarding for some ports" -j ACCEPT
	ip rule del fwmark 1
fi
