#!/bin/bash
# this script copies gluon firmware images to their public distribution points
# dependencies: rsync

SRVSSH="gw02.tecff.de"
SRVSSH_USR="root"
SRVSSH_PATH="/var/www/html/fw"
SRVSSH_DIR="v5"
if [ ! -x "$(which rsync)" ]; then
	echo "one of the dependencies is missing!"
	exit 1
fi
if [ ! "$#" -eq 1 ] || [ ! -d "$1" ]; then
	echo "please specify the source directory as the first parameter"
	exit 1
fi
SRC="$1"
if [[ "$SRC" =~ ^.+experimental.+$ ]]; then
	BRANCH="experimental"
elif [[ "$SRC" =~ ^.+beta.+$ ]]; then
	BRANCH="beta"
elif [[ "$SRC" =~ ^.+stable.+$ ]]; then
	BRANCH="stable"
fi
if [ -z "$BRANCH" ]; then
	echo "the source directory doesn't seem to be correct, it has to contain either experimental, beta or stable"
	exit 1
fi
if [ ! -d "$SRC/packages" ] || [ ! -d "$SRC/images/factory" ] || [ ! -d "$SRC/images/sysupgrade" ]; then
	echo "couldn't find at least one of the necessary directories: packages, images/factory, images/sysupgrade"
	exit 1
fi
MANIFEST="$SRC/images/sysupgrade/${BRANCH}.manifest"
if [ ! -f "$MANIFEST" ]; then
	echo "manifest missing: $MANIFEST"
	exit 1
fi
SIGCOUNT="$(sed -e '1,/^---/d' $MANIFEST | wc -l)"
if ([ "$BRANCH" == "experimental" ] && [ "$SIGCOUNT" -lt 1 ]) || \
		([ "$BRANCH" == "beta" ]    && [ "$SIGCOUNT" -lt 2 ]) || \
		([ "$BRANCH" == "stable" ]  && [ "$SIGCOUNT" -lt 3 ]); then
	echo "can't find enough signatures on the manifest file: $MANIFEST"
	exit 1
fi

echo "are you sure you backed up the old $BRANCH firmware on the update servers?"
echo "it will be overwritten if you dont interrupt now!"
sleep 5

# ssh copy
echo "starting ssh copy... (needs ssh agent redirection)"
rsync -rltv --delete $SRC/images/factory/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/$SRVSSH_DIR/$BRANCH/factory/
rsync -rltv --delete $SRC/images/sysupgrade/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/$SRVSSH_DIR/$BRANCH/sysupgrade/
if [ -d "$SRC/images/other/" ]; then
	rsync -rltv --delete $SRC/images/other/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/$SRVSSH_DIR/$BRANCH/other/
fi
rsync -rltv $SRC/packages/ $SRVSSH_USR@$SRVSSH:/$SRVSSH_PATH/modules/

echo "finished."
