#!/bin/bash
# this script backs up important data on tecff server vdesktop
# dependencies: duplicity

BSRV="u267460.your-storagebox.de"
BUSR="u267460"
BPATH="/home/backups/vdesktop/duplicity_monthly"
LOGPATH="/var/log/duplicity-vdesktop-monthly.log"

echo >> ${LOGPATH}
echo "===============================================================" >> ${LOGPATH}
echo "NEW BACKUP STARTS: $(date)" >> ${LOGPATH}

for dir in /home/ffa; do
	duplicity full --no-encryption $dir sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
	duplicity remove-older-than 12M --force sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
done
