#!/bin/sh
# IFACE is set as an environment variable by ifupdown
IPT="/sbin/iptables"
$IPT -A OUTPUT -d 192.168.0.0/16 -o $IFACE -j DROP
$IPT -A OUTPUT -d 172.16.0.0/12 -o $IFACE -j DROP
$IPT -A OUTPUT -d 169.254.0.0/16 -o $IFACE -j DROP
$IPT -A OUTPUT -d 10.0.0.0/8 -o $IFACE -j DROP
$IPT -I FORWARD -o $IFACE -m state --state INVALID -j DROP
$IPT -A OUTPUT -s 192.168.0.0/16 -o $IFACE -j DROP
$IPT -A OUTPUT -s 172.16.0.0/12 -o $IFACE -j DROP
$IPT -A OUTPUT -s 169.254.0.0/16 -o $IFACE -j DROP
$IPT -A OUTPUT -s 10.0.0.0/8 -o $IFACE -j DROP
