#!/bin/bash
# this script backs up important data on tecff server stat01
# dependencies: duplicity

BSRV="u267460.your-storagebox.de"
BUSR="u267460"
BPATH="/home/backups/stat01/duplicity"
LOGPATH="/var/log/duplicity-stat01.log"

echo >> ${LOGPATH}
echo "===============================================================" >> ${LOGPATH}
echo "NEW BACKUP STARTS: $(date)" >> ${LOGPATH}

# /var/lib/graphite
duplicity full --no-encryption /var/lib/graphite sftp://${BUSR}@${BSRV}:23/${BPATH}/graphite >> ${LOGPATH}
duplicity remove-older-than 20D --force sftp://${BUSR}@${BSRV}:23/${BPATH}/graphite >> ${LOGPATH}
