#!/bin/bash
# this script backs up important data on tecff server gw02 
# dependencies: duplicity

BSRV="u267460.your-storagebox.de"
BUSR="u267460"
BPATH="/home/backups/gw02/duplicity"
LOGPATH="/var/log/duplicity-gw02.log"

echo >> ${LOGPATH}
echo "===============================================================" >> ${LOGPATH}
echo "NEW BACKUP STARTS: $(date)" >> ${LOGPATH}

for dir in /var/local/tecff-raw /var/lib/yanic; do
	duplicity full --no-encryption $dir sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
	duplicity remove-older-than 8W --force sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
done
