#!/bin/bash
# this script backs up important data on tecff server web01
# dependencies: duplicity

BSRV="u267460.your-storagebox.de"
BUSR="u267460"
BPATH="/home/backups/web01/duplicity"
LOGPATH="/var/log/duplicity-web01.log"

echo >> ${LOGPATH}
echo "===============================================================" >> ${LOGPATH}
echo "NEW BACKUP STARTS: $(date)" >> ${LOGPATH}

for dir in /var/lib/grafana/grafana.db /home/php-privatebin /home/php-dokuwiki; do
	duplicity full --no-encryption $dir sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
	duplicity remove-older-than 3M --force sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
done

for dir in /var/lib/docker/volumes/zammad-docker-compose_zammad-backup; do
	duplicity full --no-encryption $dir sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
	duplicity remove-older-than 50D --force sftp://${BUSR}@${BSRV}:23/${BPATH}/$dir >> ${LOGPATH}
done
