#!/bin/bash
# this script saves information about nodes from B.A.T.M.A.N. to files
# dependencies: batctl, tecff-copy-data

OUTDIR="/var/local/tecff-raw"

[ -d $OUTDIR ] || mkdir $OUTDIR

batctl o > $OUTDIR/batctl_o
batctl gwl  > $OUTDIR/batctl_gwl
batctl tl > $OUTDIR/batctl_tl
# contains macs of clients -> disabled for privacy reasons
#batctl tg > $OUTDIR/batctl_tg
batctl s > $OUTDIR/batctl_s

# wait for ffmap-backend
sleep 8

tecff-copy-data
